#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import division
islem1 = "(1) toplama" 
islem2 = "(2) çıkarma"
islem3 = "(3) çarpma"
islem4 = "(4) bölme"
print (islem1)
print (islem2)
print (islem3)
print (islem4)
soru = input("Lütfen yapmak istediğiniz işlemin numarasını girin: ")

if soru == "1":
 sayi1=input("ilk sayiyi girin")
 print (sayi1)
 sayi2=input("ikinci sayiyi girin")
 print (sayi2)
 print (sayi1,"ve",sayi2,"toplamı",sayi1+sayi2,"dir")

if soru =="2":
 sayi3=input("ilk sayiyi girin")
 print (sayi3)
 sayi4 =input("ikinci sayiyi girin")
 print (sayi4)
 print (sayi3,"ve",sayi4,"farki",sayi3-sayi4,"dir")
 
if soru =="3":
 sayi5=input("ilk sayiyi girin")
 print (sayi5)
 sayi6=input("ikinci sayiyi girin")
 print (sayi6)
 print (sayi5,"ve",sayi6,"carpimi",sayi5*sayi6,"dir")

if soru =="4":
 sayi7=input("ilk sayiyi giriniz")
 print (sayi7)
 sayi8=input("ikinci sayiyi giriniz")
 print (sayi8)
 print (sayi7,"ve",sayi8,"bolumu",sayi7/sayi8,"dir")
